-- =============================================================================
-- Auto Business — Guna Milan / Ashtakoot (migration 014)
-- Full lookup tables + per-koota phal sentences + parihara + summary + mangal.
-- Uses existing Moon rashi/nakshatra/pada + Mars house — no new astronomy.
-- Idempotent. Renumbered from the uploaded 012 (taken) to 014 (next free).
-- =============================================================================
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS milan_rashi_attr (
    rashi TINYINT NOT NULL PRIMARY KEY, varna VARCHAR(12) NOT NULL, varna_rank TINYINT NOT NULL,
    vashya_group CHAR(1) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO milan_rashi_attr (rashi,varna,varna_rank,vashya_group) VALUES
(1,'Kshatriya',3,'C'),
(2,'Vaishya',2,'C'),
(3,'Shudra',1,'M'),
(4,'Brahmin',4,'J'),
(5,'Kshatriya',3,'V'),
(6,'Vaishya',2,'M'),
(7,'Shudra',1,'M'),
(8,'Brahmin',4,'K'),
(9,'Kshatriya',3,'M'),
(10,'Vaishya',2,'C'),
(11,'Shudra',1,'M'),
(12,'Brahmin',4,'J')
ON DUPLICATE KEY UPDATE varna=VALUES(varna),varna_rank=VALUES(varna_rank),vashya_group=VALUES(vashya_group);

CREATE TABLE IF NOT EXISTS milan_nakshatra_attr (
    nakshatra TINYINT NOT NULL PRIMARY KEY, yoni VARCHAR(12) NOT NULL,
    gana VARCHAR(12) NOT NULL, nadi VARCHAR(8) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO milan_nakshatra_attr (nakshatra,yoni,gana,nadi) VALUES
(1,'Ashwa','Dev','Aadi'),
(2,'Gaja','Manushya','Madhya'),
(3,'Mesha','Rakshasa','Antya'),
(4,'Sarpa','Manushya','Antya'),
(5,'Sarpa','Dev','Madhya'),
(6,'Shwan','Manushya','Aadi'),
(7,'Marjara','Dev','Aadi'),
(8,'Mesha','Dev','Madhya'),
(9,'Marjara','Rakshasa','Antya'),
(10,'Mushaka','Rakshasa','Antya'),
(11,'Mushaka','Manushya','Madhya'),
(12,'Gau','Manushya','Aadi'),
(13,'Mahisha','Dev','Aadi'),
(14,'Vyaghra','Rakshasa','Madhya'),
(15,'Mahisha','Dev','Antya'),
(16,'Vyaghra','Rakshasa','Antya'),
(17,'Mriga','Dev','Madhya'),
(18,'Mriga','Rakshasa','Aadi'),
(19,'Shwan','Rakshasa','Aadi'),
(20,'Vanara','Manushya','Madhya'),
(21,'Nakula','Manushya','Antya'),
(22,'Vanara','Dev','Antya'),
(23,'Simha','Rakshasa','Madhya'),
(24,'Ashwa','Rakshasa','Aadi'),
(25,'Simha','Manushya','Aadi'),
(26,'Gau','Manushya','Madhya'),
(27,'Gaja','Dev','Antya')
ON DUPLICATE KEY UPDATE yoni=VALUES(yoni),gana=VALUES(gana),nadi=VALUES(nadi);

CREATE TABLE IF NOT EXISTS milan_yoni_matrix (
    yoni_a VARCHAR(12) NOT NULL, yoni_b VARCHAR(12) NOT NULL, points DECIMAL(3,1) NOT NULL,
    PRIMARY KEY (yoni_a, yoni_b)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO milan_yoni_matrix (yoni_a,yoni_b,points) VALUES
('Ashwa','Ashwa',4),
('Ashwa','Gaja',2),
('Ashwa','Mesha',2),
('Ashwa','Sarpa',3),
('Ashwa','Shwan',2),
('Ashwa','Marjara',2),
('Ashwa','Mushaka',2),
('Ashwa','Gau',1),
('Ashwa','Mahisha',0),
('Ashwa','Vyaghra',1),
('Ashwa','Mriga',3),
('Ashwa','Vanara',3),
('Ashwa','Nakula',2),
('Ashwa','Simha',1),
('Gaja','Ashwa',2),
('Gaja','Gaja',4),
('Gaja','Mesha',3),
('Gaja','Sarpa',3),
('Gaja','Shwan',2),
('Gaja','Marjara',2),
('Gaja','Mushaka',2),
('Gaja','Gau',2),
('Gaja','Mahisha',3),
('Gaja','Vyaghra',1),
('Gaja','Mriga',2),
('Gaja','Vanara',3),
('Gaja','Nakula',2),
('Gaja','Simha',0),
('Mesha','Ashwa',2),
('Mesha','Gaja',3),
('Mesha','Mesha',4),
('Mesha','Sarpa',2),
('Mesha','Shwan',1),
('Mesha','Marjara',2),
('Mesha','Mushaka',1),
('Mesha','Gau',3),
('Mesha','Mahisha',3),
('Mesha','Vyaghra',1),
('Mesha','Mriga',2),
('Mesha','Vanara',0),
('Mesha','Nakula',3),
('Mesha','Simha',1),
('Sarpa','Ashwa',3),
('Sarpa','Gaja',3),
('Sarpa','Mesha',2),
('Sarpa','Sarpa',4),
('Sarpa','Shwan',2),
('Sarpa','Marjara',1),
('Sarpa','Mushaka',1),
('Sarpa','Gau',1),
('Sarpa','Mahisha',1),
('Sarpa','Vyaghra',2),
('Sarpa','Mriga',2),
('Sarpa','Vanara',2),
('Sarpa','Nakula',0),
('Sarpa','Simha',2),
('Shwan','Ashwa',2),
('Shwan','Gaja',2),
('Shwan','Mesha',1),
('Shwan','Sarpa',2),
('Shwan','Shwan',4),
('Shwan','Marjara',2),
('Shwan','Mushaka',1),
('Shwan','Gau',2),
('Shwan','Mahisha',2),
('Shwan','Vyaghra',1),
('Shwan','Mriga',0),
('Shwan','Vanara',2),
('Shwan','Nakula',1),
('Shwan','Simha',1),
('Marjara','Ashwa',2),
('Marjara','Gaja',2),
('Marjara','Mesha',2),
('Marjara','Sarpa',1),
('Marjara','Shwan',2),
('Marjara','Marjara',4),
('Marjara','Mushaka',0),
('Marjara','Gau',2),
('Marjara','Mahisha',2),
('Marjara','Vyaghra',1),
('Marjara','Mriga',3),
('Marjara','Vanara',3),
('Marjara','Nakula',2),
('Marjara','Simha',1),
('Mushaka','Ashwa',2),
('Mushaka','Gaja',2),
('Mushaka','Mesha',1),
('Mushaka','Sarpa',1),
('Mushaka','Shwan',1),
('Mushaka','Marjara',0),
('Mushaka','Mushaka',4),
('Mushaka','Gau',2),
('Mushaka','Mahisha',2),
('Mushaka','Vyaghra',2),
('Mushaka','Mriga',2),
('Mushaka','Vanara',2),
('Mushaka','Nakula',2),
('Mushaka','Simha',2),
('Gau','Ashwa',1),
('Gau','Gaja',2),
('Gau','Mesha',3),
('Gau','Sarpa',1),
('Gau','Shwan',2),
('Gau','Marjara',2),
('Gau','Mushaka',2),
('Gau','Gau',4),
('Gau','Mahisha',3),
('Gau','Vyaghra',0),
('Gau','Mriga',3),
('Gau','Vanara',2),
('Gau','Nakula',2),
('Gau','Simha',1),
('Mahisha','Ashwa',0),
('Mahisha','Gaja',3),
('Mahisha','Mesha',3),
('Mahisha','Sarpa',1),
('Mahisha','Shwan',2),
('Mahisha','Marjara',2),
('Mahisha','Mushaka',2),
('Mahisha','Gau',3),
('Mahisha','Mahisha',4),
('Mahisha','Vyaghra',1),
('Mahisha','Mriga',2),
('Mahisha','Vanara',2),
('Mahisha','Nakula',2),
('Mahisha','Simha',1),
('Vyaghra','Ashwa',1),
('Vyaghra','Gaja',1),
('Vyaghra','Mesha',1),
('Vyaghra','Sarpa',2),
('Vyaghra','Shwan',1),
('Vyaghra','Marjara',1),
('Vyaghra','Mushaka',2),
('Vyaghra','Gau',0),
('Vyaghra','Mahisha',1),
('Vyaghra','Vyaghra',4),
('Vyaghra','Mriga',1),
('Vyaghra','Vanara',1),
('Vyaghra','Nakula',2),
('Vyaghra','Simha',1),
('Mriga','Ashwa',3),
('Mriga','Gaja',2),
('Mriga','Mesha',2),
('Mriga','Sarpa',2),
('Mriga','Shwan',0),
('Mriga','Marjara',3),
('Mriga','Mushaka',2),
('Mriga','Gau',3),
('Mriga','Mahisha',2),
('Mriga','Vyaghra',1),
('Mriga','Mriga',4),
('Mriga','Vanara',2),
('Mriga','Nakula',2),
('Mriga','Simha',1),
('Vanara','Ashwa',3),
('Vanara','Gaja',3),
('Vanara','Mesha',0),
('Vanara','Sarpa',2),
('Vanara','Shwan',2),
('Vanara','Marjara',3),
('Vanara','Mushaka',2),
('Vanara','Gau',2),
('Vanara','Mahisha',2),
('Vanara','Vyaghra',1),
('Vanara','Mriga',2),
('Vanara','Vanara',4),
('Vanara','Nakula',3),
('Vanara','Simha',2),
('Nakula','Ashwa',2),
('Nakula','Gaja',2),
('Nakula','Mesha',3),
('Nakula','Sarpa',0),
('Nakula','Shwan',1),
('Nakula','Marjara',2),
('Nakula','Mushaka',2),
('Nakula','Gau',2),
('Nakula','Mahisha',2),
('Nakula','Vyaghra',2),
('Nakula','Mriga',2),
('Nakula','Vanara',3),
('Nakula','Nakula',4),
('Nakula','Simha',2),
('Simha','Ashwa',1),
('Simha','Gaja',0),
('Simha','Mesha',1),
('Simha','Sarpa',2),
('Simha','Shwan',1),
('Simha','Marjara',1),
('Simha','Mushaka',2),
('Simha','Gau',1),
('Simha','Mahisha',1),
('Simha','Vyaghra',1),
('Simha','Mriga',1),
('Simha','Vanara',2),
('Simha','Nakula',2),
('Simha','Simha',4)
ON DUPLICATE KEY UPDATE points=VALUES(points);

CREATE TABLE IF NOT EXISTS milan_vashya_matrix (
    grp_boy CHAR(1) NOT NULL, grp_girl CHAR(1) NOT NULL, points DECIMAL(3,1) NOT NULL,
    PRIMARY KEY (grp_boy, grp_girl)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO milan_vashya_matrix (grp_boy,grp_girl,points) VALUES
('C','C',2),
('C','M',1),
('C','J',1),
('C','V',0),
('C','K',1),
('M','C',1),
('M','M',2),
('M','J',0.5),
('M','V',0),
('M','K',1),
('J','C',1),
('J','M',0.5),
('J','J',2),
('J','V',0),
('J','K',1),
('V','C',0),
('V','M',0),
('V','J',0),
('V','V',2),
('V','K',0),
('K','C',1),
('K','M',1),
('K','J',1),
('K','V',0),
('K','K',2)
ON DUPLICATE KEY UPDATE points=VALUES(points);

CREATE TABLE IF NOT EXISTS milan_gana_matrix (
    gana_boy VARCHAR(12) NOT NULL, gana_girl VARCHAR(12) NOT NULL, points DECIMAL(3,1) NOT NULL,
    PRIMARY KEY (gana_boy, gana_girl)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO milan_gana_matrix (gana_boy,gana_girl,points) VALUES
('Dev','Dev',6),
('Dev','Manushya',6),
('Dev','Rakshasa',1),
('Manushya','Dev',5),
('Manushya','Manushya',6),
('Manushya','Rakshasa',0),
('Rakshasa','Dev',1),
('Rakshasa','Manushya',0),
('Rakshasa','Rakshasa',6)
ON DUPLICATE KEY UPDATE points=VALUES(points);

CREATE TABLE IF NOT EXISTS milan_koota_phal (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    koota VARCHAR(12) NOT NULL, outcome_key VARCHAR(16) NOT NULL,
    language VARCHAR(8) NOT NULL DEFAULT 'hi', points DECIMAL(3,1) NOT NULL, phal_text TEXT NOT NULL,
    updated_by_staff_id BIGINT UNSIGNED NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id), UNIQUE KEY uq_mkp (koota, outcome_key, language)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO milan_koota_phal (koota,outcome_key,language,points,phal_text) VALUES
('varna','pass','hi',1,'वर्ण मेल — स्वभाव-स्तर मिलता है; एक-दूसरे का सम्मान सहज रहेगा।'),
('varna','fail','hi',0,'वर्ण भेद — दृष्टिकोण-स्तर में अंतर; एक-दूसरे के विचारों का सम्मान सीखना होगा (बड़ा दोष नहीं)।'),
('vashya','v2','hi',2,'परस्पर आकर्षण-प्रभाव उत्तम — दोनों एक-दूसरे की बात मानेंगे।'),
('vashya','v1','hi',1,'प्रभाव संतोषजनक — पर एक साथी का पलड़ा भारी रहेगा।'),
('vashya','v05','hi',0.5,'आकर्षण सीमित — प्रभाव-संतुलन पर सचेत काम करना होगा।'),
('vashya','v0','hi',0,'स्वभाव-वर्ग विपरीत — ज़िद टकरा सकती है; खुला संवाद ज़रूरी।'),
('tara','both_good','hi',3,'तारा शुभ — स्वास्थ्य-सौभाग्य एक-दूसरे के लिए अनुकूल।'),
('tara','one_good','hi',1.5,'तारा मिश्रित — एक पक्ष का सौभाग्य-योग सामान्य; बड़ा दोष नहीं।'),
('tara','both_bad','hi',0,'तारा प्रतिकूल — स्वास्थ्य-सौभाग्य के लिए मंत्र-दान आदि उपाय अनुशंसित।'),
('yoni','y4','hi',4,'समान योनि — शारीरिक-स्वभावगत मेल उत्तम; गहरा सामंजस्य।'),
('yoni','y3','hi',3,'मित्र योनि — अच्छा शारीरिक-स्वभावगत मेल।'),
('yoni','y2','hi',2,'सम योनि — मेल सामान्य; आपसी समझ से सुधरेगा।'),
('yoni','y1','hi',1,'शत्रु योनि — स्वभाव-भिन्नता; धैर्य और स्थान (space) देना होगा।'),
('yoni','y0','hi',0,'महाशत्रु योनि — गहरा स्वभाव-वैर; यह कूट विशेष विचारणीय।'),
('maitri','m5','hi',5,'ग्रह-मैत्री श्रेष्ठ — मानसिक-वैचारिक मेल गहरा; मित्रता-भाव बना रहेगा।'),
('maitri','m4','hi',4,'ग्रह-मैत्री अच्छी — विचार अधिकतर मिलेंगे।'),
('maitri','m3','hi',3,'ग्रह-संबंध सम — वैचारिक मेल सामान्य।'),
('maitri','m1','hi',1,'ग्रह-संबंध मिश्रित (मित्र-शत्रु) — विचारों में खिंचाव संभव।'),
('maitri','m05','hi',0.5,'ग्रह-संबंध कमजोर — वैचारिक दूरी; संवाद-सेतु बनाना होगा।'),
('maitri','m0','hi',0,'ग्रह-शत्रुता — मानसिक तालमेल कठिन; यह कूट गंभीरता से देखें।'),
('gana','g6','hi',6,'गण समान/अनुकूल — प्रकृति-मेल उत्तम; घर का वातावरण सहज।'),
('gana','g5','hi',5,'गण मेल अच्छा — स्वभाव लगभग अनुकूल।'),
('gana','g1','hi',1,'देव-राक्षस गण — प्रकृति-भेद बड़ा; सहनशीलता चाहिए।'),
('gana','g0','hi',0,'गण दोष (मनुष्य-राक्षस) — स्वभाव-टकराव की आशंका; परिहार देखें।'),
('bhakoot','b7','hi',7,'भकूट शुभ — जीवन-प्रवाह, धन और परिवार-वृद्धि अनुकूल।'),
('bhakoot','b_2_12','hi',0,'द्विर्द्वादश भकूट दोष — धन-हानि व पारिवारिक कलह की आशंका; परिहार जाँचें।'),
('bhakoot','b_5_9','hi',0,'नव-पंचम भकूट दोष — संतान-विषय व वैचारिक दूरी की आशंका; परिहार जाँचें।'),
('bhakoot','b_6_8','hi',0,'षडाष्टक भकूट दोष — स्वास्थ्य-आयु की दृष्टि से सबसे गंभीर; परिहार अनिवार्यतः जाँचें।'),
('nadi','n8','hi',8,'नाड़ी भिन्न — संतान व वंश-स्वास्थ्य के लिए उत्तम; सबसे भारी कूट पूर्ण अंक।'),
('nadi','n0_aadi','hi',0,'नाड़ी दोष (आदि) — संतान-स्वास्थ्य चिंता; परिहार जाँचें।'),
('nadi','n0_madhya','hi',0,'नाड़ी दोष (मध्य) — सबसे गंभीर माना जाता है; परिहार अनिवार्यतः जाँचें।'),
('nadi','n0_antya','hi',0,'नाड़ी दोष (अन्त्य) — संतान-स्वास्थ्य चिंता; परिहार जाँचें।')
ON DUPLICATE KEY UPDATE points=VALUES(points),phal_text=VALUES(phal_text);

CREATE TABLE IF NOT EXISTS milan_parihara (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    rule_key VARCHAR(16) NOT NULL, dosha VARCHAR(12) NOT NULL, language VARCHAR(8) NOT NULL DEFAULT 'hi',
    condition_desc VARCHAR(128) NOT NULL, phal_text TEXT NOT NULL,
    updated_by_staff_id BIGINT UNSIGNED NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id), UNIQUE KEY uq_mp (rule_key, language)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO milan_parihara (rule_key,dosha,language,condition_desc,phal_text) VALUES
('nadi_p1','नाड़ी','hi','दोनों की राशि एक, नक्षत्र भिन्न','नाड़ी दोष भंग — समान राशि, भिन्न नक्षत्र।'),
('nadi_p2','नाड़ी','hi','दोनों का नक्षत्र एक, चरण भिन्न','नाड़ी दोष भंग — समान नक्षत्र, भिन्न चरण।'),
('nadi_p3','नाड़ी','hi','दोनों राशि-स्वामी एक ही ग्रह या परस्पर मित्र','नाड़ी दोष शमित — राशि-स्वामियों की मैत्री।'),
('bhakoot_p1','भकूट','hi','दोनों राशियों का स्वामी एक ही ग्रह','भकूट दोष भंग — एक ही स्वामी (जैसे मकर-कुम्भ, मेष-वृश्चिक)।'),
('bhakoot_p2','भकूट','hi','राशि-स्वामी परस्पर मित्र','भकूट दोष शमित — स्वामियों की मैत्री।'),
('gana_p1','गण','hi','राशि-स्वामी परस्पर मित्र','गण दोष शमित — स्वामियों की मैत्री।'),
('gana_p2','गण','hi','भकूट और तारा दोनों शुभ','गण दोष नरम — भकूट-तारा का सहारा।')
ON DUPLICATE KEY UPDATE condition_desc=VALUES(condition_desc),phal_text=VALUES(phal_text);

CREATE TABLE IF NOT EXISTS milan_summary (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    rule_key VARCHAR(20) NOT NULL, language VARCHAR(8) NOT NULL DEFAULT 'hi',
    min_total DECIMAL(4,1) NULL, max_total DECIMAL(4,1) NULL, phal_text TEXT NOT NULL,
    updated_by_staff_id BIGINT UNSIGNED NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id), UNIQUE KEY uq_ms (rule_key, language)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO milan_summary (rule_key,language,min_total,max_total,phal_text) VALUES
('s_33_36','hi',33,36,'उत्तम मेल — गुण-मिलान की दृष्टि से विवाह अत्यंत अनुकूल।'),
('s_25_32','hi',25,32,'बहुत अच्छा मेल — विवाह अनुकूल; दोष-खंड अवश्य देखें।'),
('s_18_24','hi',18,24,'मध्यम मेल — दोष-परिहार और मंगल-संतुलन देखकर ही आगे बढ़ें।'),
('s_0_17','hi',0,17,'गुण-मेल अपर्याप्त — गुण-मिलान की दृष्टि से अनुशंसित नहीं।'),
('o_nadi','hi',NULL,NULL,'विशेष चेतावनी: नाड़ी दोष (परिहार नहीं मिला) — कुल अंक अच्छे हों तो भी विवाह-निर्णय से पहले योग्य ज्योतिषी से परामर्श आवश्यक।'),
('o_bhakoot','hi',NULL,NULL,'विशेष चेतावनी: भकूट दोष (परिहार नहीं मिला) — {dosha_type} की आशंका; परामर्श आवश्यक।'),
('o_both','hi',NULL,NULL,'गंभीर चेतावनी: नाड़ी और भकूट दोनों दोष सक्रिय — अंक कितने भी हों, यह मिलान बिना विशेषज्ञ-परामर्श स्वीकार्य नहीं।'),
('o_mangal_mismatch','hi',NULL,NULL,'मंगल-असंतुलन: एक पत्रिका मांगलिक, दूसरी नहीं — शास्त्रोक्त परिहार (मंगल स्वराशि/उच्च, गुरु-दृष्टि आदि) जाँचें; यह अष्टकूट से अलग अनिवार्य परीक्षा है।'),
('o_mangal_both','hi',NULL,NULL,'दोनों पत्रिकाएँ मांगलिक — मंगल दोष परस्पर कट जाता है।'),
('o_mangal_none','hi',NULL,NULL,'मंगल दोष दोनों में नहीं — यह परीक्षा उत्तीर्ण।')
ON DUPLICATE KEY UPDATE min_total=VALUES(min_total),max_total=VALUES(max_total),phal_text=VALUES(phal_text);

INSERT INTO house_engine_config (cfg_key,cfg_value,notes) VALUES
('milan_vashya_by_degree','1','धनु/मकर अर्ध-भाग चन्द्र-अंश से'),
('milan_mangal_from_moon','1','मंगल दोष चन्द्र से भी'),('milan_mangal_from_venus','0','शुक्र से भी'),
('milan_mangal_second_house','1','2रे भाव को गिनें (दक्षिण मत)'),
('milan_pass_score','18','न्यूनतम स्वीकार्य कुल'),('milan_janma_tara_shubh','1','जन्म तारा शुभ गिनें')
ON DUPLICATE KEY UPDATE cfg_value=cfg_value;
-- End of migration 014.